export const pricingCards = [
  {
    id: 'quick-fix',
    title: 'QUICK FIX',
    price: '$60',
    pricePerPhoto: '$10 per photo',
    photoCount: '6 photos',
    description: '',
    features: ['24-hour turnaround', '1 revision included'],
    buttonText: 'ADD PHOTOS',
    icon: 'redeem',
    featured: false,
  },
  {
    id: 'growth-accelerator',
    title: 'GROWTH ACCELERATOR',
    price: '$100',
    pricePerPhoto: '$8.33 per photo',
    photoCount: '12 photos',
    description: '',
    features: ['3 business day turnaround', '2 revision round'],
    buttonText: 'ADD PHOTOS',
    icon: 'rocket_launch',
    featured: true,
  },
  {
    id: 'premium',
    title: 'PREMIUM',
    price: '$144',
    pricePerPhoto: '$6 per photo',
    photoCount: '24 photos',
    description: 'Maximum value for bulk editing',
    features: [
      '5 business day turnaround',
      '3 revision rounds',
      'Priority support',
    ],
    buttonText: 'ADD PHOTOS',
    icon: 'diamond',
    featured: false,
  },
];
