export const pricingCards = [
  {
    id: 'quick-fix',
    title: 'QUICK FIX',
    price: '$60',
    pricePerPhoto: '$10 per photo',
    photoCount: '6 photos',
    description: '',
    features: ['24-hour turnaround', '1 revision included'],
    buttonText: 'ADD PHOTOS',
    icon: 'redeem',
    featured: false,
  },
  {
    id: 'growth-accelerator',
    title: 'GROWTH ACCELERATOR',
    price: '$100',
    pricePerPhoto: '$8.33 per photo',
    photoCount: '12 photos',
    description: '',
    features: ['3 business day turnaround', '2 revision round'],
    buttonText: 'ADD PHOTOS',
    icon: 'rocket_launch',
    featured: true,
  },
  {
    id: 'free-trial',
    title: 'FREE TRIAL',
    price: '$0',
    pricePerPhoto: '',
    photoCount: '',
    description: 'Send us 1 real photo and see how it works',
    features: ['1 enhanced photo', '48-hour turnaround'],
    buttonText: 'GET 1 PHOTO FREE',
    icon: 'redeem',
    featured: false,
  },
];
