export const photos = [
  { id: '1', imageUrl: '/before-after/001-before.jpg', name: 'Foto 1' },
  { id: '2', imageUrl: '/before-after/002-before.jpg', name: 'Foto 2' },
  { id: '3', imageUrl: '/before-after/003-before.jpg', name: 'Foto 3' },
  { id: '4', imageUrl: '/before-after/001-before.jpg', name: 'Foto 4' },
  { id: '5', imageUrl: '/before-after/002-before.jpg', name: 'Foto 5' },
  { id: '6', imageUrl: '/before-after/003-before.jpg', name: 'Foto 6' },
  { id: '7', imageUrl: '/before-after/001-before.jpg', name: 'Foto 7' },
  { id: '8', imageUrl: '/before-after/002-before.jpg', name: 'Foto 8' },
  { id: '9', imageUrl: '/before-after/003-before.jpg', name: 'Foto 9' },
  { id: '10', imageUrl: '/before-after/001-before.jpg', name: 'Foto 10' },
  { id: '11', imageUrl: '/before-after/002-before.jpg', name: 'Foto 11' },
  { id: '12', imageUrl: '/before-after/003-before.jpg', name: 'Foto 12' },
  { id: 'placeholder', imageUrl: '', name: 'Add Photo', isPlaceholder: true },
];
